import{a as q,S as M,i as l}from"./assets/vendor-hCbx__bN.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const B="56286362-285fb1525f2ba0fd2f4df197e",$="https://pixabay.com/api/",u=async(t,r)=>(await q.get($,{params:{key:B,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data,f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),x=new M(".gallery a",{captionsData:"alt",captionDelay:250}),y=t=>{const r=t.map(({webformatURL:s,largeImageURL:n,tags:e,likes:o,views:a,comments:S,downloads:E})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${n}">
        <img class="gallery-image" src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b> ${o}</p>
        <p class="info-item"><b>Views</b> ${a}</p>
        <p class="info-item"><b>Comments</b> ${S}</p>
        <p class="info-item"><b>Downloads</b> ${E}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",r),x.refresh()},O=()=>{f.innerHTML=""},h=()=>{m.classList.remove("is-hidden")},g=()=>{m.classList.add("is-hidden")},b=()=>{p.classList.remove("is-hidden")},L=()=>{p.classList.add("is-hidden")},d=document.querySelector(".form"),R=document.querySelector(".load-more");let w="",i=1,c=0;const A=15;d.addEventListener("submit",async t=>{t.preventDefault();const r=t.currentTarget.elements["search-text"].value.trim();if(r){w=r,i=1,O(),L(),h();try{const s=await u(r);if(s.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}c=Math.ceil(s.totalHits/A),y(s.hits),i<c?b():v()}catch(s){P(s)}finally{g(),d.reset()}}});R.addEventListener("click",async()=>{i+=1,L(),h();try{const t=await u(w,i);y(t.hits),_(),i<c?b():v()}catch(t){P(t)}finally{g()}});function _(){const t=document.querySelector(".gallery-item");if(!t)return;const r=t.getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"})}function v(){l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function P(t){l.error({title:"Error",message:t.message,position:"topRight"})}
//# sourceMappingURL=index.js.map
